# Generated by Django 4.0.3 on 2022-05-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='publicKey',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='username',
            field=models.CharField(default='test', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newstip',
            name='editor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='newstip',
            name='message',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='newstip',
            name='source',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='source',
            name='username',
            field=models.CharField(default='exit', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
