# Generated by Django 4.0.3 on 2022-05-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_source_publickey_alter_editor_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='privateKey',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
